<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SubcategSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subCated=[
                    ["name"=>"DOOR LOCK","maincateg_id"=>"DDD"],
                    ["name"=>"Tower","maincateg_id"=>"DDD"],
                    ["name"=>"CABLE DRESSING","maincateg_id"=>"DDD"],
                    ["name"=>"GROUNDING","maincateg_id"=>"DDD"],
                    ["name"=>"Indoor Shelter","maincateg_id"=>"DDD"],
                    ["name"=>"Fence / Boundry Wall / Main Gate","maincateg_id"=>"DDD"],
                    ["name"=>"EXTRA MATERIAL","maincateg_id"=>"DDD"],
                    ["name"=>"Cable Tray","maincateg_id"=>"DDD"],
                    ["name"=>"DESIGN ISSUE","maincateg_id"=>"DDD"],
                    ["name"=>"PATHWAY DAMAGE ","maincateg_id"=>"DDD"],
                    ["name"=>"DG ISSUES","maincateg_id"=>"DDD"],
                    ["name"=>"Emergency Light ","maincateg_id"=>"DDD"],
                    ["name"=>"Main DB","maincateg_id"=>"DDD"],
                    ["name"=>"BATTERY BACKUP","maincateg_id"=>"DDD"],
                    ["name"=>"Compound Damage","maincateg_id"=>"DDD"],
                    ["name"=>"ACDB","maincateg_id"=>"DDD"],
                    ["name"=>"Paint Job","maincateg_id"=>"DDD"],
                    ["name"=>"OTHERS","maincateg_id"=>"DDD"],
                    ["name"=>"LABELING","maincateg_id"=>"DDD"],
                    ["name"=>"PADLOCK","maincateg_id"=>"DDD"],
                    ["name"=>"RECTIFIER","maincateg_id"=>"DDD"],
                    ["name"=>"AIR_CONDITIONER","maincateg_id"=>"DDD"],
                    ["name"=>"Board","maincateg_id"=>"DDD"],
                    ["name"=>"Other","maincateg_id"=>"DDD"],
                    ["name"=>"Sand","maincateg_id"=>"DDD"],
                    ["name"=>"RT Ladder","maincateg_id"=>"DDD"],
                    ["name"=>"HOUSEKEEPING","maincateg_id"=>"DDD"],
                    ["name"=>"LOG BOOK","maincateg_id"=>"DDD"],
                    ["name"=>"Antenna Pole","maincateg_id"=>"DDD"],
                    ["name"=>"Fire Panel","maincateg_id"=>"DDD"],
                    ["name"=>"Fire Panel Battery","maincateg_id"=>"DDD"],
                    ["name"=>"EXTERNAL ALARM","maincateg_id"=>"DDD"],
                    ["name"=>"Rectifeir Module","maincateg_id"=>"DDD"],
                    ["name"=>"ILLUMINATION LIGHT","maincateg_id"=>"DDD"],
                    ["name"=>"Delta_Filter","maincateg_id"=>"DDD"],
                    ["name"=>"Compressor","maincateg_id"=>"DDD"],
                    ["name"=>"CIVIL_WORK","maincateg_id"=>"DDD"],
                    ["name"=>"Foundation","maincateg_id"=>"DDD"],
                    ["name"=>"REMOTE MISSING","maincateg_id"=>"DDD"],
                    ["name"=>"TEMPERATURE SENSOR","maincateg_id"=>"DDD"],
                    ["name"=>"DB","maincateg_id"=>"DDD"],
                    ["name"=>"AVIATION_LIGHT","maincateg_id"=>"DDD"],
                    ["name"=>"COW","maincateg_id"=>"DDD"],
                    ["name"=>"Housekeeping ","maincateg_id"=>"DDD"],
                    ["name"=>"Shelter","maincateg_id"=>"DDD"],
                    ["name"=>"Emergency Light","maincateg_id"=>"DDD"],
                    ["name"=>"Delta Cabinet","maincateg_id"=>"DDD"],
                    ["name"=>"Remote Batteries","maincateg_id"=>"DDD"],
                    ["name"=>"Sensor","maincateg_id"=>"DDD"],
                    ["name"=>"Rectifier Module","maincateg_id"=>"DDD"],
                    ["name"=>"Ladder Broken","maincateg_id"=>"DDD"],
                    ["name"=>"Door Sensor","maincateg_id"=>"DDD"],
                    ["name"=>"Air Con Sensor","maincateg_id"=>"DDD"],
                    ["name"=>"Ladder","maincateg_id"=>"DDD"],
                    ["name"=>"Aviation Light","maincateg_id"=>"DDD"],
                    ["name"=>"Compound","maincateg_id"=>"DDD"],
                    ["name"=>"Designe Issue","maincateg_id"=>"DDD"],
                    ["name"=>"Aviatin Light","maincateg_id"=>"DDD"],
                    ["name"=>"Battert Backup","maincateg_id"=>"DDD"],
                    ["name"=>"House Keeping","maincateg_id"=>"DDD"],
                    ["name"=>"Air Conditioner","maincateg_id"=>"DDD"],
                    ["name"=>"Maing DB","maincateg_id"=>"DDD"],
                    ["name"=>" CABLE DRESSING","maincateg_id"=>"DDD"],
                    ["name"=>"RECTIFIER ALARMS","maincateg_id"=>"DDD"],
                    ["name"=>"Ladder Broken ","maincateg_id"=>"DDD"],
                    ["name"=>"AVIATION LIGHT BOARD","maincateg_id"=>"DDD"],
                    ["name"=>"WRONG INSTALLATION","maincateg_id"=>"DDD"],
                    ["name"=>"DELTA _AIRCON FAULTY","maincateg_id"=>"DDD"],
                    ["name"=>"sector blockage ","maincateg_id"=>"DDD"],
                    ["name"=>"Power connection","maincateg_id"=>"DDD"],
                    ["name"=>"Fuel  ","maincateg_id"=>"DDD"],
                    ["name"=>"Sun Shade","maincateg_id"=>"DDD"],
                    ["name"=>"FIRE PANEL ","maincateg_id"=>"DDD"],
                    ["name"=>"huawei ETP48300 Display","maincateg_id"=>"DDD"],
                    ["name"=>"EXTERNAL ALARMS ","maincateg_id"=>"DDD"],
                    ["name"=>"UNSAFE LADDER","maincateg_id"=>"DDD"],
                    ["name"=>"Microwave Antenna","maincateg_id"=>"DDD"],
                    ["name"=>"FACP BATTERY ","maincateg_id"=>"DDD"],
                    ["name"=>"AC SPD  FAULTY","maincateg_id"=>"DDD"],
                    ["name"=>"VSAT ","maincateg_id"=>"DDD"],
                    ["name"=>"RECTIFIER  MODULE","maincateg_id"=>"DDD"],
                    ["name"=>"Tower Light","maincateg_id"=>"DDD"],
                    ["name"=>"Smoke Sensor","maincateg_id"=>"DDD"],
                    ["name"=>"PCB KIT","maincateg_id"=>"DDD"],
                    ["name"=>"LEAKAGE","maincateg_id"=>"DDD"],
                    ["name"=>"LOGO TIMER","maincateg_id"=>"DDD"],
                    ["name"=>"COW tyre","maincateg_id"=>"DDD"],
                    ["name"=>"LOGOTIMER","maincateg_id"=>"DDD"],
                    ["name"=>"Fire Equipment","maincateg_id"=>"DDD"],
                    ["name"=>"AVR","maincateg_id"=>"DDD"],
                    ["name"=>"COMPRESSOR 2.5 Rotary","maincateg_id"=>"DDD"],
                    ["name"=>"DELTA RECTIFIER","maincateg_id"=>"DDD"],
                    ["name"=>"Filter","maincateg_id"=>"DDD"],
                    ["name"=>"MISSING","maincateg_id"=>"DDD"],
                    ["name"=>" SHELTER","maincateg_id"=>"DDD"],
                    ["name"=>"DUMMY MISSING","maincateg_id"=>"DDD"],
                    ["name"=>"EXPIRY","maincateg_id"=>"DDD"],
                    ["name"=>"REMOTE","maincateg_id"=>"DDD"],
                    ["name"=>"DG","maincateg_id"=>"DDD"],
                    ["name"=>"ANTENNA GROUNDING","maincateg_id"=>"DDD"],
                    ["name"=>" SHELTER DOOR","maincateg_id"=>"DDD"],
                    ["name"=>"AIR CONTIONER","maincateg_id"=>"DDD"],
                    ["name"=>"Main Gate","maincateg_id"=>"DDD"],
                    ["name"=>"OD CABINET AIR CON","maincateg_id"=>"DDD"],
                    ["name"=>"AIR CONCITIONER","maincateg_id"=>"DDD"],
                    ["name"=>"AIR CONDITIONER ID","maincateg_id"=>"DDD"],
                    ["name"=>"LIGHTNING SYSTEM","maincateg_id"=>"DDD"],
                    ["name"=>"AIR CONTIONER OD","maincateg_id"=>"DDD"],
            ];
        }
    }
